package in.lingayat.we.models.enums;

public enum Qualification {
    QUALIFICATION_TWELTH,
    QUALIFICATION_TENTH,
    QUALIFICATION_BSC,
    QUALIFICATION_MSC,
    QUALIFICATION_BCOM,
    QUALIFICATION_MCOM,
    QUALIFICATION_BA,
    QUALIFICATION_MA,
    QUALIFICATION_PHD,
    QUALIFICATION_MBBS,
    QUALIFICATION_BE,
    QUALIFICATION_BTECH,
    QUALIFICATION_ME,
    QUALIFICATION_MTECH,
    QUALIFICATION_ITI,
    QUALIFICATION_MD,
    QUALIFICATION_BPHARM,
    QUALIFICATION_MPHARM,
    QUALIFICATION_BED,
    QUALIFICATION_MED,
    QUALIFICATION_BARCH,
    QUALIFICATION_MARCH,
    QUALIFICATION_OTHER
}
